spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
        - id: accounts-api
          uri: lb://ACCOUNTS-API
          predicates:
            - Path=/accounts/**
        - id: posts-api
          uri: lb://POSTS-API
          predicates:
            - Path=/posts/**
        - id: chat-api
          uri: lb://CHAT-API
          predicates:
            - Path=/chat/**

  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

server:
  port: 8087