spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
        - id: accounts-api
          uri: lb://ACCOUNTS-API
          predicates:
            - Path=/accounts/**,/follows/**,/follow-requests/**
        - id: posts-api
          uri: lb://POSTS-API
          predicates:
            - Path=/posts/**,/comments/**
        - id: chat-api
          uri: lb://CHAT-API
          predicates:
            - Path=/chats/**,/messages/**
        - id: offers-api
          uri: lb://OFFERS-API
          predicates:
            - Path=/offers/**


server:
  port: 8087