spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
        - id: accounts-api
          uri: http://localhost:8080
          predicates:
            - Path=/accounts/**,/follows/**,/follow-requests/**
          filters:
            - AuthFilter
        - id: posts-api
          uri: http://localhost:8082
          predicates:
            - Path=/posts/**,/comments/**
          filters:
            - AuthFilter
        - id: chat-api
          uri: http://localhost:8084
          predicates:
            - Path=/chats/**,/messages/**
          filters:
            - AuthFilter
        - id: offers-api
          uri: http://localhost:8083
          predicates:
            - Path=/offers/**,/companies/**
          filters:
            - AuthFilter

server:
  port: 8087