spring:
  cloud:
    gateway:
      routes:
        - id: accounts-api-public
          uri: http://localhost:8080
          predicates:
            - Path=/accounts/public-search
        - id: accounts-api
          uri: http://localhost:8080
          predicates:
            - Path=/accounts/**,/follows/**,/follow-requests/**
          filters:
            - AuthFilter
        - id: auth-api
          uri: http://localhost:8181
          predicates:
            - Path=/login,/register,/validate-token
        - id: posts-api-public
          uri: http://localhost:8082
          predicates:
            - Path=/posts/account/*
        - id: posts-api
          uri: http://localhost:8082
          predicates:
            - Path=/posts/**,/comments/**
          filters:
            - AuthFilter
        - id: chat-api
          uri: http://localhost:8084
          predicates:
            - Path=/chats/**,/messages/**
          filters:
            - AuthFilter
        - id: offers-api
          uri: http://localhost:8083
          predicates:
            - Path=/offers/**
          filters:
            - AuthFilter
        - id: agent-api
          uri: http://localhost:8089
          predicates:
            - Path=/company-comment/**,/companies/**,/company-request/**,/rates**
          filters:
            - AuthFilter

api:
  auth: http://localhost:8181

server:
  port: 8087